export const PHRASES_DATA: Record<string, string[]> = {
  'DINERO': [
    "Poderoso caballero es don Dinero. – Francisco de Quevedo.",
    "El dinero es el estiércol del diablo; pero es un abono excelente. – Proverbio popular.",
    "El dinero es una nueva forma de esclavitud, distinguible de la antigua solo por el hecho de que es impersonal. – León Tolstói.",
    "El dinero es la esencia alienada del trabajo y de la existencia del hombre. – Karl Marx.",
    "El dinero no es más que un valor de cambio; su único valor real es lo que se puede comprar con él. – Adam Smith.",
    "El dinero es como el sexto sentido; sin él, no puedes usar los otros cinco. – Somerset Maugham.",
    "El dinero es un sol de bolsillo. – Victor Hugo.",
    "El dinero es el lenguaje universal. – Aphra Behn.",
    "La moneda es la libertad acuñada. – Fiódor Dostoyevski.",
    "El dinero es el dios de nuestro tiempo. – Friedrich Nietzsche.",
    "El dinero es el único poder al que todos se inclinan. – Ralph Waldo Emerson.",
    "El capital es trabajo muerto que, al modo de un vampiro, vive solo de succionar trabajo vivo. – Karl Marx.",
    "El dinero es una garantía de que tendremos lo que queramos en el futuro. – Aristóteles.",
    "El oro hace que lo feo parezca hermoso. – Molière.",
    "El dinero es el gran nivelador. – Thomas Carlyle.",
    "Un banco es un lugar donde te prestan un paraguas cuando hace buen tiempo y te lo piden cuando empieza a llover. – Robert Frost.",
    "El dinero es como el agua: si no corre, se estanca y se pudre. – Refrán anónimo.",
    "El dinero no cambia a la gente, solo la desenmascara. – Henry Ford.",
    "El dinero habla un lenguaje que todas las naciones entienden. – Aphra Behn.",
    "El dinero es un sirviente increíble, pero un amo terrible. – Francis Bacon.",
    "La riqueza no consiste en tener grandes posesiones, sino en tener pocas necesidades. – Epicteto.",
    "El sabio no ama la riqueza, pero prefiere tenerla. – Séneca.",
    "La riqueza es la esclava del sabio y la dueña del necio. – Séneca.",
    "Nada es suficiente para quien lo suficiente es poco. – Epicuro.",
    "El que es rico en amigos es pobre en nada. – Proverbio.",
    "La pobreza no viene por la disminución de las riquezas, sino por la multiplicación de los deseos. – Platón.",
    "Muchos hombres no poseen su riqueza, su riqueza los posee a ellos. – Robert G. Ingersoll.",
    "El hombre que tiene poco no es pobre; el que desea mucho es el verdadero pobre. – Séneca.",
    "La riqueza de un hombre se mide por la cantidad de cosas de las que puede prescindir. – Henry David Thoreau.",
    "Si quieres ser rico, no te afanes en aumentar tus bienes, sino en disminuir tu codicia. – Epicuro.",
    "La verdadera riqueza consiste en el uso, no en la posesión. – Esopo.",
    "El dinero es una de las cosas más baratas. Lo más caro es lo que no se puede comprar. – Proverbio oriental.",
    "¿Quién es rico? El que se regocija en su porción. – El Talmud.",
    "Un hombre es rico en proporción a las cosas que puede permitirse dejar en paz. – Thoreau.",
    "La riqueza es un gran estorbo para el aprendizaje. – Epicuro.",
    "Es más fácil que un camello pase por el ojo de una aguja, que un rico entre en el reino de Dios. – Mateo 19:24.",
    "La opulencia es un robo, si no se comparte. – Erasmo de Rotterdam.",
    "El desprecio de las riquezas era en los filósofos un deseo oculto de vengar su mérito del abandono de la fortuna. – François de La Rochefoucauld.",
    "No estimes el dinero ni más ni menos de lo que vale, porque es un buen siervo y un mal amo. – Alejandro Dumas.",
    "Aquel que cree que el dinero lo hace todo, termina haciendo todo por dinero. – Voltaire.",
    "El dinero no da la felicidad, pero procura una sensación tan parecida, que solo un especialista muy avanzado podría verificar la diferencia. – Woody Allen.",
    "La felicidad no consiste en tener mucho dinero, sino en tener lo que uno desea. – Aristóteles.",
    "El dinero es la felicidad humana en abstracto. – Arthur Schopenhauer.",
    "Quien cree que el dinero no compra la felicidad, no sabe dónde ir de compras. – Gertrude Stein.",
    "Prefiero llorar en un Rolls Royce que ser feliz en una bicicleta. – Patrizia Reggiani.",
    "El dinero no da la felicidad, pero calma los nervios. – Sean O'Casey.",
    "La felicidad es una dirección, no un lugar. – Sydney J. Harris.",
    "Tener dinero es como tener salud: su ausencia se nota, su presencia se olvida. – Anónimo.",
    "El dinero compra el placer, pero no el amor. – Proverbio.",
    "Demasiado dinero es tan peligroso como la falta de él. – Proverbio.",
    "Hay gente tan pobre que solo tiene dinero. – Atribuido a Bob Marley.",
    "La falta de dinero es la raíz de todo mal. – Mark Twain (parodiando la Biblia).",
    "Cuando el dinero habla, la verdad calla. – Proverbio chino.",
    "El dinero no compra la vida. – Bob Marley.",
    "El éxito es tener lo que quieres; la felicidad es querer lo que tienes. – Dale Carnegie.",
    "No se puede servir a Dios y al Dinero. – Jesucristo.",
    "El dinero es un valor que permite no depender de nadie. – Albert Camus.",
    "La felicidad no es un objetivo, es un subproducto. – Eleanor Roosevelt.",
    "El dinero es como el brazo derecho: útil si se usa, inútil si se guarda. – Anónimo.",
    "El dinero solo es útil cuando se gasta. – Atribuido a varios economistas.",
    "La avaricia es un pozo sin fondo que agota a la persona en un esfuerzo interminable por satisfacer su necesidad. – Erich Fromm.",
    "El mundo tiene suficiente para las necesidades de todos, pero no para la codicia de todos. – Mahatma Gandhi.",
    "La codicia es la raíz de todos los males. – 1 Timoteo 6:10.",
    "El que ama el dinero no se saciará de dinero. – Eclesiastés 5:10.",
    "La ambición es el último refugio del fracaso. – Oscar Wilde.",
    "El dinero es como el agua salada: cuanto más se bebe, más sed da. – Arthur Schopenhauer.",
    "La riqueza es como el humo; si no sale por la chimenea, ahoga al dueño. – Refrán.",
    "El lujo es una necesidad que empieza donde acaba la necesidad. – Coco Chanel.",
    "El ahorro es una virtud, especialmente cuando tus antepasados lo han practicado por ti. – Winston Churchill.",
    "Un necio y su dinero pronto se separan. – Thomas Tusser.",
    "Nada es tan difícil de soportar como una serie de días buenos. – Goethe (sobre la complacencia de la riqueza).",
    "El que persigue dos conejos, no atrapa ninguno. – Confucio.",
    "El precio de cualquier cosa es la cantidad de vida que intercambias por ella. – Henry David Thoreau.",
    "La especulación es solo una palabra para designar la esperanza de los tontos. – Anónimo.",
    "Donde hay dinero, hay demonios. – San Jerónimo.",
    "La propiedad es un robo. – Pierre-Joseph Proudhon.",
    "El capital no tiene patria. – Napoleón Bonaparte.",
    "La riqueza consiste mucho más en el disfrute que en la posesión. – Aristóteles.",
    "El que tiene dinero tiene en el bolsillo a los que no lo tienen. – León Tolstói.",
    "Si el dinero es tu esperanza de independencia, nunca la tendrás. – Henry Ford.",
    "El tiempo es dinero. – Benjamin Franklin.",
    "Gasta tu dinero en las cosas que el dinero puede comprar. Gasta tu tiempo en las cosas que el dinero no puede comprar. – Haruki Murakami.",
    "La economía es el arte de sacar el mayor provecho de la vida. – George Bernard Shaw.",
    "No pongas tu confianza en el dinero, pero pon tu dinero en confianza. – Oliver Wendell Holmes.",
    "Cuando el último árbol sea cortado y el último pez pescado, el hombre se dará cuenta de que el dinero no se puede comer. – Proverbio Cree.",
    "El capitalista te venderá la soga con la que lo vas a colgar. – Atribuido a Lenin.",
    "El mercado es un lugar creado para que los hombres se engañen unos a otros. – Anacarsis.",
    "El dinero es una herramienta. Te llevará a donde desees, pero no te reemplazará como conductor. – Ayn Rand.",
    "Un hombre con un millón de dólares es tan feliz como si fuera rico. – Arnold Schwarzenegger (con humor).",
    "El presupuesto le dice a tu dinero a dónde ir, en lugar de preguntarte a dónde se fue. – John Maxwell.",
    "El dinero es el único poder que no necesita ser justificado. – Anónimo.",
    "Si quieres saber lo que Dios piensa del dinero, solo mira a la gente a la que se lo ha dado. – Dorothy Parker.",
    "El trabajo es el padre y la tierra es la madre de la riqueza. – William Petty.",
    "La clase media es aquella que tiene que trabajar para pagar por las cosas que no necesita. – Anónimo.",
    "La inflación es cuando pagas quince dólares por el corte de pelo de diez dólares que antes pagabas cinco cuando tenías pelo. – Sam Ewing.",
    "El interés compuesto es la octava maravilla del mundo. – Albert Einstein.",
    "No puedes comprar el cielo con dinero. – Proverbio.",
    "La bolsa es un juego que consiste en pasar de mano en mano una brasa encendida. – Nathaniel Rothschild.",
    "La prosperidad es el mejor protector de la paz. – James Madison.",
    "Al final, no importa cuánto dinero tengas, solo cuántas vidas tocaste. – Anónimo.",
  ],
  'AMOR': [
    "Platón: Al contacto del amor, todo el mundo se vuelve poeta.",
    "Aristóteles: El amor se compone de una sola alma que habita en dos cuerpos.",
    "Séneca: Si quieres ser amado, ama.",
    "Epicuro: No es tanto la ayuda de nuestros amigos lo que nos ayuda, sino la confianza de su ayuda.",
    "Platón: El amor es la alegría de los buenos, la reflexión de los sabios, el asombro de los incrédulos.",
    "San Agustín: La medida del amor es amar sin medida.",
    "Cicerón: Nadie hay que no ame; la cuestión es qué es lo que ama.",
    "Plutarco: Donde no hay amor, no hay dolor.",
    "Sófocles: Una palabra nos libera de todo el peso y el dolor de la vida: esa palabra es amor.",
    "Platón: El amor es una enfermedad mental grave. (Incluso los genios tienen sus días cínicos).",
    "Friedrich Nietzsche: Lo que se hace por amor, ocurre siempre más allá del bien y del mal.",
    "Jean-Paul Sartre: El amor es una empresa temeraria.",
    "Simone de Beauvoir: El día que sea posible para la mujer amar no por debilidad sino por fortaleza, el amor será para ella una fuente de vida y no un peligro mortal.",
    "Baruch Spinoza: El amor es una alegría acompañada por la idea de una causa externa.",
    "Arthur Schopenhauer: Todo amor, por etéreo que quiera ser, tiene sus raíces en el instinto sexual.",
    "José Ortega y Gasset: En el amor nos parece que nos hemos quedado solos con el universo.",
    "Immanuel Kant: El corazón humano tiene un deseo de amor, pero también un deseo de independencia.",
    "Blaise Pascal: El corazón tiene razones que la razón no entiende.",
    "Søren Kierkegaard: El amor es todo, es la mayor alegría, pero es también el dolor más profundo.",
    "Friedrich Nietzsche: No es la falta de amor, sino la falta de amistad lo que hace que los matrimonios sean infelices.",
    "Erich Fromm: El amor infantil sigue el principio: 'Amo porque me aman'. El amor maduro sigue el principio: 'Me aman porque amo'.",
    "Antoine de Saint-Exupéry: Amar no es mirarse el uno al otro; es mirar juntos en la misma dirección.",
    "Gabriel Marcel: Amar a alguien es decirle: tú no morirás jamás.",
    "Stendhal: El amor es una flor deliciosa, pero es preciso tener el valor de ir a buscarla al borde de un precipicio horrible.",
    "Viktor Frankl: El amor es la meta última y más alta a la que puede aspirar el hombre.",
    "Carl Jung: Donde el amor impera, no hay deseo de poder; y donde el poder predomina, falta el amor.",
    "Erich Fromm: El amor no es algo natural. Más bien requiere disciplina, concentración, paciencia y fe.",
    "Octavio Paz: El amor es una apuesta temeraria por la libertad.",
    "Bertrand Russell: Temer al amor es temer a la vida, y los que temen a la vida ya están medio muertos.",
    "Miguel de Unamuno: Se quiere más lo que se ha conquistado con fatiga.",
    "Lao Tzu: Ser profundamente amado por alguien te da fuerza, mientras que amar a alguien profundamente te da valor.",
    "Rumi: Tu tarea no es buscar el amor, sino simplemente buscar y encontrar todas las barreras dentro de ti que has construido contra él.",
    "Buda: Tú mismo, tanto como cualquier otro en el universo entero, mereces tu amor y afecto.",
    "Khalil Gibran: El amor no da nada más que a sí mismo y no toma nada más que de sí mismo.",
    "Confucio: Dondequiera que vayas, ve con todo tu corazón.",
    "Jiddu Krishnamurti: En el momento en que tienes amor, no estás siguiendo a nadie.",
    "Rabindranath Tagore: El amor es un misterio infinito, porque no tiene causa que lo explique.",
    "Rumi: Donde hay ruinas, hay esperanza de un tesoro.",
    "Hafez: El amor es el puente entre tú y todo.",
    "Daisaku Ikeda: El amor debe ser una fuerza que nos impulse a ser mejores.",
    "William Shakespeare: El amor no mira con los ojos, sino con el alma.",
    "Victor Hugo: La suprema felicidad de la vida es saber que eres amado por ti mismo o, más exactamente, a pesar de ti mismo.",
    "Dante Alighieri: El amor mueve el sol y las demás estrellas.",
    "Lord Byron: El amor del hombre es algo aparte en su vida; para la mujer, es su existencia entera.",
    "Oscar Wilde: Amarse a uno mismo es el comienzo de un romance de por vida.",
    "Johann Wolfgang von Goethe: Amamos a una persona porque ella es lo que nosotros no somos.",
    "Federico García Lorca: El amor es el beso que se da con el alma.",
    "Pablo Neruda: Para mi corazón basta tu pecho, para tu libertad bastan mis alas.",
    "Jorge Luis Borges: Estar contigo o no estar contigo es la medida de mi tiempo.",
    "Gustave Flaubert: El amor es un manantial que se agota si no se alimenta de algo nuevo cada día.",
    "François de La Rochefoucauld: Es más difícil ocultar los sentimientos que tenemos que fingir los que no tenemos.",
    "George Bernard Shaw: El primer amor es un poco de locura y mucha curiosidad.",
    "Michel de Montaigne: Si me preguntan por qué le amaba, siento que solo puede expresarse respondiendo: porque era él; porque era yo.",
    "David Hume: El amor es la emoción más poderosa de la mente humana.",
    "Immanuel Kant: La amistad es el amor sin alas.",
    "Zygmunt Bauman: En el amor líquido, los lazos son frágiles y las relaciones son precarias.",
    "Albert Camus: No ser amado es una simple desventura; la verdadera desgracia es no amar.",
    "Hannah Arendt: El amor, por su propia naturaleza, no es mundano.",
    "Thomas Hobbes: El deseo de amor es el deseo de poder sobre los demás.",
    "Byung-Chul Han: El amor hoy se ha convertido en una mercancía de consumo.",
    "Hegel: El amor es la conciencia de mi unidad con el otro.",
    "Francis Bacon: Es imposible amar y ser sabio al mismo tiempo.",
    "Lev Tolstói: El que solo conoce a su mujer y la ama, sabe más de mujeres que el que ha conocido a mil.",
    "Simone Weil: Amar es aceptar que el otro sea distinto a uno.",
    "Fiodor Dostoyevski: ¿Qué es el infierno? Yo sostengo que es el sufrimiento de no poder amar.",
    "Charles Bukowski: El amor es una forma de prejuicio. Amas lo que necesitas.",
    "Giacomo Casanova: El amor es tres cuartas partes curiosidad.",
    "Honoré de Balzac: El amor es la poesía de los sentidos.",
    "Denis Diderot: Solo las grandes pasiones pueden elevar el alma a grandes cosas.",
    "Ralph Waldo Emerson: Todo el mundo ama a un amante.",
    "Henry David Thoreau: No hay más remedio para el amor que amar más.",
    "Albert Einstein: El amor es mejor maestro que el deber.",
    "Virginia Woolf: Nadie ha amado como nosotros amamos.",
    "Emily Dickinson: El amor es anterior a la vida, posterior a la muerte.",
    "Marcel Proust: Casi no hay amor en el que no haya una parte de invención.",
    "Milan Kundera: El amor es el deseo de encontrar la mitad perdida de nosotros mismos.",
    "Isabel Allende: Tal vez estamos en este mundo para buscar el amor, encontrarlo y perderlo, una y otra vez.",
    "Julio Cortázar: Ven a dormir conmigo: no haremos el amor, él nos hará.",
    "Mario Benedetti: Sé que voy a quererte sin preguntas, sé que vas a quererme sin respuestas.",
    "Gabriel García Márquez: El problema del matrimonio es que se acaba todas las noches después de hacer el amor, y hay que volver a reconstruirlo todas las mañanas antes del desayuno.",
    "Sandro Pertini: El amor es la fuerza que transforma y mejora el alma del mundo.",
    "Erasmo de Rotterdam: En el amor, la locura es siempre un componente esencial.",
    "Molière: El amor es un gran maestro: nos enseña a ser lo que nunca fuimos.",
    "Alfred de Musset: El amor es un sueño, pero el matrimonio es la alarma.",
    "Benjamin Franklin: Si quieres ser amado, sé amable.",
    "Mark Twain: Para obtener el valor total de la alegría, debes tener a alguien con quien dividirla.",
    "Paulo Coelho: Cuando amamos, siempre nos esforzamos por ser mejores de lo que somos.",
    "John Lennon: Todo lo que necesitas es amor. (Filosofía pop, pero filosofía al fin).",
    "Anatole France: Es mejor haber amado y perdido que jamás haber amado.",
    "Hermann Hesse: Si sé lo que es el amor, es por ti.",
    "Felicité de Lamennais: El amor y la fe son las dos fuerzas que mueven al mundo.",
    "Jean de La Bruyère: Solo hay un amor verdadero, pero hay mil copias diferentes.",
    "Madame de Staël: El amor es el emblema de la eternidad; confunde toda noción de tiempo.",
    "Pierre Corneille: El amor que nace de repente es el más difícil de curar.",
    "Graham Greene: Es imposible amar y ser políticamente correcto.",
    "Aldous Huxley: El amor expulsa el miedo y, a su vez, el miedo expulsa al amor.",
    "Umberto Eco: El amor es más sabio que la sabiduría.",
    "Zygmunt Bauman: Amar significa abrirse al destino.",
    "Simone de Beauvoir: El amor auténtico debería basarse en el reconocimiento mutuo de dos libertades.",
    "Anónimo (Sabiduría Popular): El amor es como el Wi-Fi: está en el aire, pero no todos tienen la contraseña.",
  ],
  'ANSIEDAD': [
    "La ansiedad es el vértigo de la libertad. — Søren Kierkegaard.",
    "El hombre está condenado a ser libre; porque una vez arrojado al mundo, es responsable de todo lo que hace. — Jean-Paul Sartre.",
    "No es el miedo a algo concreto, sino el miedo a la nada misma. — Martin Heidegger.",
    "La existencia precede a la esencia. — Jean-Paul Sartre.",
    "La ansiedad es la disposición fundamental que nos coloca ante la nada. — Martin Heidegger.",
    "Elegir es ser libre, y la libertad es la fuente de toda angustia. — Søren Kierkegaard.",
    "El hombre no es nada más que lo que hace de sí mismo. — Jean-Paul Sartre.",
    "La angustia es el modo de ser de la libertad como conciencia del ser. — Jean-Paul Sartre.",
    "Aceptar nuestra finitud es el primer paso para superar la ansiedad por la muerte. — Martin Heidegger.",
    "La vida comienza al otro lado de la desesperación. — Jean-Paul Sartre.",
    "Sufrimos más a menudo en la imaginación que en la realidad. — Séneca.",
    "No son las cosas las que nos perturban, sino nuestra interpretación de ellas. — Epicteto.",
    "Tienes poder sobre tu mente, no sobre los acontecimientos externos. Date cuenta de esto y encontrarás la fuerza. — Marco Aurelio.",
    "La felicidad es un flujo de vida tranquilo. — Zenón de Citio.",
    "¿Por qué habrías de preocuparte por el futuro? Vive el presente con rectitud. — Marco Aurelio.",
    "El hombre que sufre antes de que sea necesario, sufre más de lo necesario. — Séneca.",
    "Nuestra ansiedad no proviene de pensar en el futuro, sino de querer controlarlo. — Jalil Gibran (influencia estoica).",
    "La mayor parte de lo que decimos y hacemos no es necesario. — Marco Aurelio.",
    "No busques que los eventos sucedan como quieres; desea que sucedan como suceden. — Epicteto.",
    "La tranquilidad es nada menos que el buen orden de la mente. — Marco Aurelio.",
    "Si estás ansioso, estás viviendo en el futuro. Si estás en paz, estás viviendo en el presente. — Lao Tzu (atribuida).",
    "La raíz del sufrimiento es el apego. — Buda.",
    "Nada es permanente en este mundo malvado, ni siquiera nuestros problemas. — Charlie Chaplin (perspectiva budista).",
    "Si tiene solución, ¿por qué te preocupas? Si no la tiene, ¿por qué te preocupas? — Proverbio budista.",
    "El hoy es el único tiempo que tenemos para ser felices. — Thich Nhat Hanh.",
    "La ansiedad es como una mecedora: te da algo que hacer pero no te lleva a ninguna parte. — Proverbio indio.",
    "Fluye con todo lo que ocurra y deja que tu mente sea libre. — Zhuangzi.",
    "La paz mental llega cuando dejas de querer cambiar a los demás y te enfocas en ti. — Proverbio Zen.",
    "No habites en el pasado, no sueñes con el futuro, concentra la mente en el momento presente. — Buda.",
    "Bebe tu té lentamente y con reverencia, como si fuera el eje sobre el que gira la tierra. — Thich Nhat Hanh.",
    "La ansiedad es el precio que pagamos por la civilización. — Sigmund Freud.",
    "A lo que te resistes, persiste. — Carl Jung.",
    "La preocupación es una forma de arrogancia: creer que puedes controlar el mañana. — Alan Watts.",
    "No soy lo que me pasó, soy lo que elijo ser. — Carl Jung.",
    "La ansiedad es un ruido que indica que algo en nuestra alma necesita atención. — Alain de Botton.",
    "Vivir es lo más raro del mundo. La mayoría de la gente existe, eso es todo. — Oscar Wilde.",
    "La mente es su propio lugar, y en sí misma puede hacer un cielo del infierno. — John Milton.",
    "El hombre moderno vive bajo la ilusión de saber lo que quiere, mientras que en realidad solo quiere lo que se supone que debe querer. — Erich Fromm.",
    "La soledad es el camino por el que el destino se busca a sí mismo. — Hermann Hesse.",
    "Nadie puede construirte el puente sobre el cual debas cruzar el río de la vida, nadie excepto tú mismo. — Friedrich Nietzsche.",
    "Debemos imaginar a Sísifo feliz. — Albert Camus.",
    "En medio del invierno, aprendí por fin que había en mí un verano invencible. — Albert Camus.",
    "Lo que no me mata, me hace más fuerte. — Friedrich Nietzsche.",
    "Quien tiene un porqué para vivir, puede soportar casi cualquier cómo. — Viktor Frankl.",
    "La mayor arma contra el estrés es nuestra capacidad de elegir un pensamiento sobre otro. — William James.",
    "El secreto de la existencia humana no solo está en vivir, sino en saber para qué se vive. — Fiódor Dostoyevski.",
    "No dejes que el ruido de las opiniones ajenas silencie tu propia voz interior. — Steve Jobs.",
    "La vida es una tragedia de cerca, pero una comedia de lejos. — Charlie Chaplin.",
    "La ansiedad no vacía el mañana de sus penas, sino que vacía el hoy de su fuerza. — Charles Spurgeon.",
    "Amor Fati: Ama tu destino, que es en realidad tu propia vida. — Friedrich Nietzsche.",
    "Pensar demasiado es el arte de crear problemas que no existían.",
    "La calma es el superpoder del hombre moderno.",
    "El miedo llamó a la puerta. La fe abrió. No había nadie.",
    "No cruces el puente hasta que llegues a él.",
    "La ansiedad es solo energía sin dirección.",
    "El futuro es un lugar que no existe más que en tu mente.",
    "Tu mente es un jardín, tus pensamientos son las semillas.",
    "Lo que te preocupa, te esclaviza. — Locke.",
    "La paciencia es la forma más suave de la valentía.",
    "Incluso la noche más oscura terminará y el sol saldrá. — Victor Hugo.",
    "Ser consciente es estar vivo.",
    "La duda es el principio de la sabiduría, pero la ansiedad es el fin del descanso.",
    "No te tomes la vida tan en serio, al fin y al cabo no saldrás vivo de ella. — Elbert Hubbard.",
    "La paz comienza con una sonrisa. — Teresa de Calcuta.",
    "El miedo es el camino hacia el lado oscuro. — Yoda (Filosofía pop).",
    "La realidad es aquello que, incluso cuando dejas de creer en ello, no desaparece. — Philip K. Dick.",
    "La ansiedad es un maestro estricto, pero un maestro al fin.",
    "Aprender a dejar ir es la clave de la libertad.",
    "Todo pasa, nada queda.",
    "La vida es cambio, la resistencia es dolor.",
    "Nuestros pensamientos son los arquitectos de nuestro destino.",
    "La imaginación es una herramienta, no dejes que sea tu carcelera.",
    "El ruido exterior no es nada comparado con el ruido interior.",
    "La ansiedad es el parásito de la anticipación.",
    "No somos lo que pensamos, somos los que observan los pensamientos.",
    "Domina tus sentidos y dominarás tu miedo.",
    "La claridad mental es el resultado del desapego emocional.",
    "Preocuparse es como pagar una deuda que no debes.",
    "La mente es un excelente servidor, pero un amo terrible.",
    "El silencio es el lenguaje de la paz.",
    "Acepta lo que es, deja ir lo que fue, ten fe en lo que será.",
    "Tu respiración es tu ancla en la tormenta.",
    "La vulnerabilidad no es debilidad, es nuestra mayor medida de coraje. — Brené Brown.",
    "No puedes detener las olas, pero puedes aprender a surfear. — Jon Kabat-Zinn.",
    "La alegría de vivir viene de encuentros con nuevas experiencias. — Christopher McCandless.",
    "Sé aquí ahora. — Ram Dass.",
    "Cada mañana nacemos de nuevo. Lo que hacemos hoy es lo que más importa.",
    "La cura para todo es siempre agua salada: el sudor, las lágrimas o el mar. — Isak Dinesen.",
    "Mira hacia las estrellas y no hacia tus pies. — Stephen Hawking.",
    "La única salida es a través. — Robert Frost.",
    "La felicidad no es algo hecho. Viene de tus propias acciones. — Dalai Lama.",
    "El universo no tiene la obligación de tener sentido para ti. — Neil deGrasse Tyson.",
    "Haz lo que puedas, con lo que tengas, donde estés. — Theodore Roosevelt.",
    "Un viaje de mil millas comienza con un solo paso. — Lao Tzu.",
    "No dejes que lo que no puedes hacer interfiera con lo que puedes hacer.",
    "La simplicidad es la máxima sofisticación. — Da Vinci.",
    "La vida es 10% lo que te pasa y 90% cómo reaccionas.",
    "Tu hogar es tu mente; asegúrate de que sea un lugar agradable para vivir.",
    "La ansiedad susurra mentiras sobre el futuro; la verdad grita en el presente.",
    "Esto también pasará. — Leyenda sufí.",
  ],
  'SALUD': [
    "Que tu alimento sea tu medicina y tu medicina tu alimento. – Hipócrates",
    "La salud es la mayor de las bendiciones humanas. – Hipócrates",
    "Mente sana en cuerpo sano. – Juvenal",
    "Parte de la curación está en la voluntad de sanar. – Séneca",
    "La salud no es un bien que se posee, sino una armonía que se mantiene. – Plotino",
    "El médico cura, la naturaleza sana. – Aristóteles",
    "No se puede curar el cuerpo sin curar el alma. – Sócrates",
    "La enfermedad es un impedimento para el cuerpo, pero no para la voluntad. – Epicteto",
    "Nada es tan perjudicial para la salud como el cambio frecuente de remedios. – Séneca",
    "La vida no es solo vivir, sino estar bien. – Marcial",
    "La brevedad de la vida no es el problema, sino el desperdicio de la salud. – Séneca",
    "El que tiene salud tiene esperanza; y el que tiene esperanza, lo tiene todo. – Proverbio Árabe",
    "La salud es la medida de la libertad. – Pericles",
    "No hay placer que valga si el cuerpo sufre. – Epicuro",
    "El exceso en la comida es el enemigo de la vida. – Cicerón",
    "La templanza es la mejor medicina. – Platón",
    "Un cuerpo débil debilita el espíritu. – Jean-Jacques Rousseau (influencia clásica)",
    "La salud es el silencio de los órganos. – René Leriche",
    "Cuida tu cuerpo; es el único lugar que tienes para vivir. – Anónimo",
    "La mejor medicina de todas es enseñarle a la gente cómo no necesitarla. – Hipócrates",
    "La salud es la mayor posesión. – Lao Tse",
    "Mantener el cuerpo en buena salud es un deber; de lo contrario, no podremos mantener nuestra mente fuerte y clara. – Buda",
    "El hombre sabio debería considerar que la salud es la mayor de las bendiciones humanas. – Buda",
    "La tensión es quien crees que deberías ser. La relajación es quien eres. – Proverbio Chino",
    "Un viaje de mil millas comienza con un solo paso hacia el bienestar. – Lao Tse",
    "La salud es el regalo más grande, la satisfacción la mayor riqueza. – Buda",
    "Donde hay paz y meditación, no hay ansiedad ni duda. – Francisco de Asís",
    "El cuerpo es el templo del espíritu. – Proverbio Hindú",
    "Quien gana salud, gana tiempo. – Proverbio Chino",
    "La mente es el maestro, el cuerpo es el sirviente. – Dhammapada",
    "La verdadera curación es el retorno a la unidad. – Tao Te Ching",
    "El agua que corre nunca se estanca; el cuerpo que se mueve nunca se enferma. – Proverbio Chino",
    "La salud no se compra, se cultiva. – Confucio",
    "La enfermedad entra por la boca, pero sale por la mente. – Proverbio Zen",
    "Estar en armonía con el Tao es la salud suprema. – Zhuangzi",
    "La risa es el mejor desinfectante del alma. – Proverbio Oriental",
    "Si no cuidas tu salud hoy, mañana tendrás que cuidar tu enfermedad. – Proverbio Chino",
    "El silencio es el sueño que nutre la sabiduría. – Francis Bacon",
    "La paciencia es la raíz de la salud. – Proverbio Japonés",
    "No busques la salud fuera de ti mismo. – Dogen",
    "La salud es ese estado en el que el individuo se siente libre de obstáculos. – Immanuel Kant",
    "La mayor de las locuras es sacrificar la salud por cualquier otro tipo de felicidad. – Arthur Schopenhauer",
    "He decidido ser feliz porque es bueno para la salud. – Voltaire",
    "La salud es la armonía de la vida dentro de nosotros. – Ralph Waldo Emerson",
    "Un cuerpo sano es la habitación del alma; uno enfermo, su prisión. – Francis Bacon",
    "La salud es la primera riqueza. – Ralph Waldo Emerson",
    "La enfermedad es el campo de batalla de la vida. – Friedrich Nietzsche",
    "Aquel que tiene un 'porqué' para vivir, puede soportar casi cualquier 'cómo'. – Viktor Frankl",
    "La salud es una relación entre tú y tu cuerpo. – Terry Guillemets",
    "Lo que no me mata, me hace más fuerte. – Friedrich Nietzsche",
    "La salud es el equilibrio entre el hombre y su entorno. – Karl Marx",
    "El hombre gasta su salud para ganar dinero y luego gasta su dinero para recuperar su salud. – Dalai Lama",
    "La verdadera salud es la capacidad de vivir plenamente la propia vida. – Michel Foucault",
    "No es señal de salud estar bien adaptado a una sociedad profundamente enferma. – Jiddu Krishnamurti",
    "La salud es la libertad de ser quien eres. – Sartre",
    "Para disfrutar de una buena salud, uno debe ser humilde. – Dostoievski",
    "La medicina es el arte de acompañar al paciente mientras la naturaleza cura. – Voltaire",
    "La salud es la base de toda virtud. – Thomas Jefferson",
    "Sin salud, la vida no es vida; es solo un estado de languidez. – François Rabelais",
    "La salud es un estado de completa armonía física, mental y social. – OMS (Definición filosófica moderna)",
    "Tus pensamientos son los arquitectos de tu destino físico. – David Viscott",
    "El corazón alegre es la mejor medicina. – Proverbio Bíblico",
    "La enfermedad es el grito del alma que no ha sido escuchada. – C.G. Jung",
    "La curación es un proceso, no un evento. – Anne Wilson Schaef",
    "Nuestros cuerpos son nuestros jardines; nuestras voluntades son los jardineros. – William Shakespeare",
    "La mente tiene una gran influencia sobre el cuerpo, y las enfermedades a menudo tienen allí su origen. – Molière",
    "La salud no es algo que simplemente te sucede; es algo que tú creas. – Deepak Chopra",
    "El síntoma es solo el mensajero. – Anónimo",
    "Para cambiar el cuerpo, primero debes cambiar la mente. – Platón",
    "El cuerpo nunca miente. – Martha Graham",
    "La salud es la integración del alma con el cuerpo. – Stefan Zweig",
    "Sentirse bien es la forma más alta de inteligencia. – Anónimo",
    "El miedo es el mayor enemigo de la salud. – Mahatma Gandhi",
    "La calma es la base de la vitalidad. – Alejandro Jodorowsky",
    "La salud mental es tan importante como la física, porque el cerebro es el motor del cuerpo. – Anónimo",
    "Una mala actitud es como un neumático pinchado; no puedes ir a ningún lado hasta que lo cambies. – Anónimo",
    "El estrés es la basura de la vida moderna; todos la generamos, pero si no la eliminas, te consume. – Terri Guillemets",
    "La salud es un estado de paz interior. – Wayne Dyer",
    "Toda curación es, en última instancia, curación espiritual. – Mary Baker Eddy",
    "La risa es el sol que ahuyenta el invierno del rostro humano. – Victor Hugo",
    "Aquel que no tiene tiempo para el ejercicio, tendrá que encontrar tiempo para la enfermedad. – Edward Stanley",
    "La salud es como el dinero: nunca tenemos una idea real de su valor hasta que la perdemos. – Josh Billings",
    "Dormir es la cadena de oro que une la salud y nuestros cuerpos. – Thomas Dekker",
    "La mejor medicina es el descanso y el ayuno. – Benjamin Franklin",
    "Caminar es la mejor medicina del hombre. – Hipócrates",
    "La salud es el resultado de la disciplina. – Aristóteles",
    "La moderación es el hilo de seda que corre a través de la perla de todas las virtudes. – Joseph Hall",
    "Come poco, cena menos; que la salud de todo el cuerpo se fragua en la oficina del estómago. – Miguel de Cervantes",
    "La salud es el ahorro de la vida. – Proverbio Popular",
    "Un exterior saludable comienza desde el interior. – Robert Urich",
    "La salud es un derecho, pero también una responsabilidad. – Anónimo",
    "No esperes a estar enfermo para valorar la salud. – Anónimo",
    "La vida es corta, pero la mala salud la hace parecer larga. – Anónimo",
    "La salud es la música del cuerpo. – Anónimo",
    "El cuerpo es una máquina perfecta si el operario es sabio. – Anónimo",
    "La salud no es el destino, es el vehículo para llegar a tus sueños. – Anónimo",
    "La prevención vale más que mil curas. – Erasmo de Rotterdam",
    "El optimismo es el mejor tónico. – Anónimo",
    "La salud es la poesía de la vida biológica. – Anónimo",
    "Ama a tu cuerpo para que tu alma quiera habitar en él. – Anónimo",
  ],
  'EXITO': [
    "El éxito es la capacidad de ir de fracaso en fracaso sin perder el entusiasmo. – Winston Churchill.",
    "No importa qué tan lento vayas, siempre y cuando no te detengas. – Confucio.",
    "Nuestra mayor gloria no está en no caer nunca, sino en levantarnos cada vez que caemos. – Confucio.",
    "El éxito es 1% inspiración y 99% transpiración. – Thomas Edison.",
    "La caída no es un fracaso. El fracaso es quedarse donde uno se cayó. – Sócrates.",
    "El hombre que mueve montañas empieza apartando piedrecitas. – Proverbio Chino.",
    "Para tener éxito, primero debemos creer que podemos. – Nikos Kazantzakis.",
    "El éxito no es el final, el fracaso no es fatal: es el valor para continuar lo que cuenta. – Winston Churchill.",
    "La perseverancia es el trabajo duro que haces después de cansarte del trabajo duro que ya hiciste. – Newt Gingrich.",
    "Solo aquellos que se atreven a fracasar a lo grande pueden lograr mucho. – Robert F. Kennedy.",
    "No intentes convertirte en un hombre de éxito, sino en un hombre de valor. – Albert Einstein.",
    "El éxito consiste en obtener lo que se desea. La felicidad, en disfrutar lo que se obtiene. – Ralph Waldo Emerson.",
    "Un hombre es un éxito si se levanta por la mañana y se acuesta por la noche, y entre medias hace lo que quiere hacer. – Bob Dylan.",
    "El éxito no es la clave de la felicidad. La felicidad es la clave del éxito. – Albert Schweitzer.",
    "Si no diseñas tu propio plan de vida, es probable que caigas en el plan de otra persona. – Jim Rohn.",
    "El éxito es simplemente la aplicación diaria de la disciplina. – Jim Rohn.",
    "¿Qué es el éxito? Reír mucho y a menudo; ganar el respeto de personas inteligentes. – Ralph Waldo Emerson.",
    "El verdadero éxito es la superación de uno mismo. – Séneca.",
    "No hay éxito sin integridad. – Napoleon Hill.",
    "El éxito es la realización progresiva de un ideal digno. – Earl Nightingale.",
    "La felicidad de tu vida depende de la calidad de tus pensamientos. – Marco Aurelio.",
    "El impedimento para la acción avanza la acción. Lo que se interpone en el camino se convierte en el camino. – Marco Aurelio.",
    "No es que tengamos poco tiempo, es que perdemos mucho. – Séneca.",
    "Si quieres ser rico, no te afanes en aumentar tus bienes, sino en disminuir tu codicia. – Epicuro.",
    "La mejor venganza es ser diferente a quien causó el daño. – Marco Aurelio.",
    "Ningún hombre es libre si no es dueño de sí mismo. – Epicteto.",
    "La riqueza no consiste en tener grandes posesiones, sino en tener pocas necesidades. – Epicteto.",
    "El éxito externo es un 'indiferente preferido'; la virtud es el único bien real. – Zenón de Citio.",
    "No busques que los eventos sucedan como quieres, sino desea que sucedan como suceden. – Epicteto.",
    "La suerte es lo que sucede cuando la preparación se encuentra con la oportunidad. – Séneca.",
    "Saber no es suficiente; debemos aplicar. Querer no es suficiente; debemos hacer. – Johann Wolfgang von Goethe.",
    "El éxito es hijo de la audacia. – Benjamin Disraeli.",
    "Solo se vive una vez, pero si lo haces bien, una vez es suficiente. – Mae West.",
    "El futuro depende de lo que hagas hoy. – Mahatma Gandhi.",
    "Haz lo que puedas, con lo que tengas, donde estés. – Theodore Roosevelt.",
    "La mejor manera de predecir el futuro es creándolo. – Peter Drucker.",
    "El riesgo más grande es no correr ningún riesgo. – Mark Zuckerberg (filosofía moderna).",
    "Inicia donde estás. Usa lo que tienes. Haz lo que puedes. – Arthur Ashe.",
    "La acción es la clave fundamental de todo éxito. – Pablo Picasso.",
    "El camino hacia el éxito siempre está en construcción. – Lily Tomlin.",
    "Tanto si piensas que puedes como si piensas que no puedes, tienes razón. – Henry Ford.",
    "La mente es todo. Te conviertes en lo que piensas. – Buda.",
    "El éxito es un estado mental. Si quieres éxito, empieza a pensar en ti mismo como un éxito. – Joyce Brothers.",
    "Cambia tus pensamientos y cambiarás tu mundo. – Norman Vincent Peale.",
    "El éxito no es para los que creen que pueden, sino para los que saben que pueden. – Anónimo.",
    "Nuestra vida es lo que nuestros pensamientos crean. – Marco Aurelio.",
    "La confianza en sí mismo es el primer secreto del éxito. – Ralph Waldo Emerson.",
    "Un hombre sabio creará más oportunidades de las que encuentra. – Francis Bacon.",
    "El entusiasmo es el motor del éxito. – Napoléon Bonaparte.",
    "Aquel que tiene un porqué para vivir se puede enfrentar a todos los cómos. – Friedrich Nietzsche.",
    "Somos lo que hacemos repetidamente. La excelencia, entonces, no es un acto, sino un hábito. – Aristóteles.",
    "La raíz de la educación es amarga, pero sus frutos son dulces. – Aristóteles.",
    "El placer en el trabajo pone la perfección en el trabajo. – Aristóteles.",
    "El éxito es la recompensa del esfuerzo bien dirigido. – Aristóteles (parafraseado).",
    "No basta con ganar la guerra; es más importante organizar la paz. – Aristóteles.",
    "La inteligencia consiste no solo en el conocimiento, sino también en la destreza de aplicar los conocimientos en la práctica. – Aristóteles.",
    "La victoria tiene muchas madres, pero la derrota es huérfana. – John F. Kennedy.",
    "Donde tus talentos y las necesidades del mundo se cruzan, ahí está tu vocación. – Aristóteles.",
    "La calidad no es un acto, es un hábito. – Aristóteles.",
    "El ignorante afirma, el sabio duda y reflexiona. – Aristóteles.",
    "Para evitar la crítica, no digas nada, no hagas nada, no seas nada. – Elbert Hubbard.",
    "El éxito es la mejor venganza. – Frank Sinatra.",
    "Si quieres alcanzar la excelencia, puedes llegar allí hoy mismo. A partir de este segundo, deja de hacer un trabajo menos que excelente. – Thomas J. Watson.",
    "El éxito atrae a los amigos, el fracaso los pone a prueba. – Publio Siro.",
    "No conozco la clave del éxito, pero la clave del fracaso es tratar de complacer a todo el mundo. – Bill Cosby.",
    "Un líder es alguien que conoce el camino, recorre el camino y muestra el camino. – John C. Maxwell.",
    "El éxito es un maestro terrible. Seduce a la gente inteligente a pensar que no pueden perder. – Bill Gates.",
    "El mayor error que puedes cometer en la vida es el miedo continuo a que cometerás uno. – Elbert Hubbard.",
    "A menudo, el éxito se logra por aquellos que no saben que el fracaso es inevitable. – Coco Chanel.",
    "La gente juzga el éxito por lo que ven, no por lo que sacrificaste. – Anónimo.",
    "El éxito sin honor es un plato sazonado que no quita el hambre. – Guadalupe Nettel.",
    "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de alguien más. – Steve Jobs.",
    "El único lugar donde el éxito viene antes que el trabajo es en el diccionario. – Vidal Sassoon.",
    "El sentido de la vida es encontrar tu don. El propósito de la vida es entregarlo. – Pablo Picasso.",
    "No cuentes los días, haz que los días cuenten. – Muhammad Ali.",
    "El éxito es dejar el mundo un poco mejor. – Bessie Anderson Stanley.",
    "Vive como si fueras a morir mañana. Aprende como si fueras a vivir siempre. – Mahatma Gandhi.",
    "La pregunta no es quién me va a dejar, sino quién me va a detener. – Ayn Rand.",
    "El éxito no es cuánto dinero tienes, sino la diferencia que marcas en la vida de las personas. – Michelle Obama.",
    "Haz lo que amas y el dinero seguirá. – Marsha Sinetar.",
    "El hombre está condenado a ser libre; porque una vez lanzado al mundo, él es responsable de todo lo que hace. – Jean-Paul Sartre.",
    "La libertad es lo que haces con lo que te han hecho. – Jean-Paul Sartre.",
    "En medio del invierno, aprendí por fin que había en mí un verano invencible. – Albert Camus.",
    "El éxito no se mide por lo que logras, sino por la oposición que has encontrado. – Orison Swett Marden.",
    "Cada dificultad superada es un éxito acumulado. – Anónimo.",
    "La vida es un 10% lo que me pasa y un 90% cómo reacciono a ello. – Charles Swindoll.",
    "No busques el camino rápido, busca el camino correcto. – Anónimo.",
    "Ser uno mismo en un mundo que constantemente intenta hacerte otra cosa es el mayor logro. – Ralph Waldo Emerson.",
    "El éxito es el resultado de la preparación, el trabajo duro y aprender del fracaso. – Colin Powell.",
    "Para tener éxito, tu deseo de éxito debe ser mayor que tu miedo al fracaso. – Bill Cosby.",
    "Veni, Vidi, Vici (Vine, vi, vencí). – Julio César.",
    "Sapere Aude (Atrévete a saber). – Immanuel Kant.",
    "El éxito es un viaje, no un destino. – Ben Sweetland.",
    "Si puedes soñarlo, puedes hacerlo. – Walt Disney.",
    "La disciplina es el puente entre metas y logros. – Jim Rohn.",
    "El éxito es simplemente nunca rendirse. – Anónimo.",
    "Menos es más. – Ludwig Mies van der Rohe.",
    "Pienso, luego existo. – René Descartes (el éxito de la conciencia).",
    "Todo lo que siempre has querido está al otro lado del miedo. – George Addair.",
    "El éxito es despertar cada mañana con el alma en paz. – Anónimo.",
  ],
  'FELICIDAD': [
    "Aristóteles: La felicidad depende de nosotros mismos.",
    "Aristóteles: La felicidad es el significado y el propósito de la vida, todo el objetivo y el fin de la existencia humana.",
    "Sócrates: El secreto de la felicidad no se encuentra en la búsqueda de más, sino en el desarrollo de la capacidad para disfrutar de menos.",
    "Platón: El hombre que hace que todo lo que lleve a la felicidad dependa de él mismo, y no de los demás, ha adoptado el mejor plan para vivir feliz.",
    "Epicuro: No es lo que tenemos, sino lo que disfrutamos, lo que constituye nuestra abundancia.",
    "Epicuro: El que no considera lo que tiene como la riqueza más grande, es desdichado, aunque sea el dueño del mundo.",
    "Séneca: La verdadera felicidad es disfrutar del presente, sin dependencia ansiosa sobre el futuro.",
    "Séneca: Nadie puede vivir felizmente si solo se mira a sí mismo, si lo convierte todo en una cuestión de su propia utilidad.",
    "Marco Aurelio: La felicidad de tu vida depende de la calidad de tus pensamientos.",
    "Marco Aurelio: Muy poco se necesita para hacer una vida feliz; está todo dentro de ti mismo, en tu forma de pensar.",
    "Epicteto: Solo hay un camino hacia la felicidad y es dejar de preocuparse por las cosas que están más allá del poder de nuestra voluntad.",
    "Epicteto: La felicidad no consiste en adquirir y gozar, sino en no desear nada.",
    "Demócrito: La felicidad no reside en las posesiones, ni en el oro, la felicidad habita en el alma.",
    "Pitágoras: No digas que eres feliz antes de que hayas muerto. (Haciendo referencia a la integridad de una vida completa).",
    "Heráclito: Si la felicidad consistiera en los placeres del cuerpo, llamaríamos felices a los bueyes cuando encuentran algarrobas para comer.",
    "Buda: No hay camino a la felicidad: la felicidad es el camino.",
    "Buda: La paz viene de adentro. No la busques afuera.",
    "Buda: Miles de velas pueden encenderse a partir de una sola, y la vida de esa vela no se acortará. La felicidad nunca disminuye al ser compartida.",
    "Lao Tse: Si estás deprimido, estás viviendo en el pasado. Si estás ansioso, estás viviendo en el futuro. Si estás en paz, estás viviendo en el presente.",
    "Lao Tse: Al darse cuenta de que nada falta, el mundo entero le pertenece a uno.",
    "Confucio: Cuanto más medita el hombre en los buenos pensamientos, mejor será su mundo y el mundo en general.",
    "Confucio: Todos los hombres desean la felicidad, pero pocos la buscan en la moderación.",
    "Zhuangzi: La felicidad es la ausencia de la búsqueda de la felicidad.",
    "Rumi: Tu tarea no es buscar el amor, sino simplemente buscar y encontrar todas las barreras dentro de ti que has construido contra él.",
    "Mahatma Gandhi: La felicidad es cuando lo que piensas, lo que dices y lo que haces están en armonía.",
    "Jiddu Krishnamurti: La felicidad es extraña; llega cuando no la buscas.",
    "Lin Yutang: Si puedes pasar una tarde perfectamente inútil de una manera perfectamente inútil, has aprendido a vivir.",
    "Kahlil Gibran: Vuestros hijos no son vuestros hijos... ellos vienen a través de ti, pero no de ti. (Sobre la felicidad de la libertad).",
    "Sun Tzu: La suprema felicidad es la paz.",
    "Proverbio Zen: Si no puedes encontrar la felicidad en el lugar donde estás, ¿dónde esperas encontrarla?",
    "Immanuel Kant: La felicidad no es un ideal de la razón, sino de la imaginación.",
    "Immanuel Kant: Para ser feliz se necesita algo que hacer, alguien a quien amar y algo que esperar.",
    "Baruch Spinoza: La felicidad no es el premio de la virtud, sino la virtud misma.",
    "John Stuart Mill: He aprendido a buscar mi felicidad limitando mis deseos en vez de satisfacerlos.",
    "John Stuart Mill: Es mejor ser un ser humano insatisfecho que un cerdo satisfecho; mejor ser Sócrates insatisfecho que un necio satisfecho.",
    "David Hume: La felicidad de la vida consiste en tener siempre algo que hacer, alguien a quien amar y algo que esperar. (Coincidiendo con Kant).",
    "Voltaire: He decidido ser feliz porque es bueno para la salud.",
    "Voltaire: Buscamos la felicidad, pero sin saber dónde, como los borrachos buscan su casa, sabiendo que tienen una.",
    "Jean-Jacques Rousseau: El dinero que se tiene es el instrumento de la libertad; el que se busca es el de la servidumbre.",
    "Blaise Pascal: Todos los hombres buscan ser felices. Esto no tiene excepción.",
    "Blaise Pascal: La felicidad es un artículo de maravilla: cuanto más se da, más le queda a uno.",
    "Montesquieu: Si solo quisiéramos ser felices, sería fácil; pero queremos ser más felices que los demás.",
    "Thomas Jefferson: No es la riqueza ni el esplendor, sino la tranquilidad y el trabajo los que proporcionan la felicidad.",
    "Denis Diderot: Solo hay un deber y es el de ser feliz.",
    "Gottfried Leibniz: Amar es encontrar la propia felicidad en la felicidad de otro.",
    "Friedrich Nietzsche: La felicidad es el sentimiento de que el poder crece, de que una resistencia ha sido superada.",
    "Friedrich Nietzsche: El destino de los hombres está hecho de momentos felices, toda la vida no los tiene, pero sí momentos felices.",
    "Arthur Schopenhauer: La felicidad consiste en la repetición frecuente del placer.",
    "Arthur Schopenhauer: Es difícil encontrar la felicidad dentro de uno mismo, pero es imposible encontrarla en otro lugar.",
    "Arthur Schopenhauer: Nuestra felicidad depende de lo que somos, de nuestra individualidad, mientras que a menudo solo tenemos en cuenta nuestro destino.",
    "Søren Kierkegaard: La puerta de la felicidad se abre hacia fuera; quien trata de derribarla hacia dentro, la cierra.",
    "Søren Kierkegaard: La mayoría de los hombres persiguen el placer con tal premura que pasan de largo por delante de la felicidad.",
    "Albert Camus: Nunca serás feliz si sigues buscando en qué consiste la felicidad. Nunca vivirás si buscas el significado de la vida.",
    "Albert Camus: Pero, ¿qué es la felicidad sino la sencilla armonía entre un hombre y la vida que lleva?",
    "Jean-Paul Sartre: La felicidad no es hacer lo que uno quiere, sino querer lo que uno hace.",
    "Simone de Beauvoir: En sí misma, la homosexualidad es tan limitante como la heterosexualidad: lo ideal debería ser capaz de amar a una mujer o a un hombre; a cualquier ser humano, sin sentir miedo, inhibición o obligación. (Sobre la felicidad de la autenticidad).",
    "Ralph Waldo Emerson: Por cada minuto que estás enojado pierdes sesenta segundos de felicidad.",
    "Henry David Thoreau: La felicidad es como una mariposa; cuanto más la persigues, más se te escapa. Pero si te sientas tranquilamente, puede posarse sobre ti.",
    "Fiódor Dostoyevski: El hombre es infeliz porque no sabe que es feliz. Eso es todo.",
    "Leo Tolstoy: Si quieres ser feliz, sé.",
    "Bertrand Russell: De todas las formas de precaución, la precaución en el amor es quizás la más fatal para la verdadera felicidad.",
    "Bertrand Russell: La felicidad que es puramente física y personal no es de mucha importancia.",
    "Viktor Frankl: La felicidad no puede ser perseguida; debe ser una consecuencia de vivir una vida con sentido.",
    "Viktor Frankl: A un hombre se le puede quitar todo excepto una cosa: la última de las libertades humanas —la elección de la actitud personal ante un conjunto de circunstancias—.",
    "Erich Fromm: La felicidad es el indicador de que el hombre ha encontrado la respuesta al problema de la existencia humana.",
    "Hannah Arendt: La felicidad pública consiste en el derecho del ciudadano a acceder a la esfera pública.",
    "José Ortega y Gasset: Felicidad es la vida dedicada a ocupaciones para las cuales cada hombre tiene vocación.",
    "Jorge Luis Borges: He cometido el peor pecado que un hombre puede cometer. No he sido feliz.",
    "Aldous Huxley: La felicidad no se logra mediante la búsqueda consciente de la felicidad; es generalmente el subproducto de otras actividades.",
    "C.S. Lewis: La alegría es el negocio serio del cielo.",
    "Michel Foucault: No me preguntes quién soy y no me pidas que permanezca invariable. (La felicidad como cambio).",
    "Zygmunt Bauman: En una sociedad de consumo, la felicidad es el estado de estar en el proceso de comprar. (Crítica).",
    "Albert Einstein: Una mesa, una silla, un cuenco de fruta y un violín; ¿qué más necesita un hombre para ser feliz?",
    "Albert Einstein: Si quieres vivir una vida feliz, átala a una meta, no a personas o cosas.",
    "William James: El éxito o el fracaso dependen más de la actitud que de la capacidad.",
    "Anónimo: La felicidad es una dirección, no un lugar.",
    "Stendhal: La belleza es una promesa de felicidad.",
    "Oscar Wilde: Algunos causan felicidad allá donde van; otros, siempre que se van.",
    "Oscar Wilde: Vivir es lo más raro del mundo. La mayoría de la gente existe, eso es todo.",
    "Mark Twain: La mejor manera de alegrarte a ti mismo es intentar alegrar a alguien más.",
    "Hermann Hesse: La felicidad es amor, nada más. El que sabe amar es feliz.",
    "Franklin D. Roosevelt: La felicidad no reside en la mera posesión de dinero; reside en la alegría del logro, en la emoción del esfuerzo creativo.",
    "Helen Keller: Tu éxito y felicidad dependen de ti. Decide mantenerte feliz y tu alegría y tú formaréis un anfitrión invencible contra las dificultades.",
    "Benjamin Franklin: La felicidad humana no se logra con grandes golpes de suerte, que pueden ocurrir raras veces, sino con pequeñas cosas que ocurren todos los días.",
    "Ernest Hemingway: La felicidad en la gente inteligente es la cosa más rara que conozco.",
    "George Bernard Shaw: No tenemos más derecho a consumir felicidad sin producirla que a consumir riqueza sin producirla.",
    "Winston Churchill: El éxito no es el final, el fracaso no es fatal: es el coraje para continuar lo que cuenta.",
    "Eleanor Roosevelt: Alguien me preguntó una vez cuál creía que era la cualidad más importante para ser feliz, y respondí: 'La capacidad de asombro'.",
    "Anatole France: Es mejor entender poco que entender mal.",
    "Graham Greene: Siempre hay un momento en la infancia cuando la puerta se abre y deja entrar al futuro.",
    "Gabriel García Márquez: No hay medicina que cure lo que no cura la felicidad.",
    "Julio Cortázar: Cada vez que entres en un lugar, no olvides que la felicidad está en los detalles.",
    "Friedrich Schiller: Aquel que ha hecho lo mejor para su tiempo, ha vivido para todos los tiempos.",
    "Dalai Lama: La felicidad no es algo que ya esté hecho. Viene de tus propias acciones.",
    "Thich Nhat Hanh: No hay camino hacia la paz, la paz es el camino.",
    "Simone Weil: La atención es la forma más rara y pura de generosidad.",
    "Søren Kierkegaard: La vida solo puede ser comprendida mirando hacia atrás, pero debe ser vivida mirando hacia adelante.",
    "Sigmund Freud: La ciencia moderna aún no ha producido un medicamento tranquilizador tan eficaz como lo son unas pocas palabras bondadosas.",
    "Wayne Dyer: Si cambias la forma en que miras las cosas, las cosas que miras cambian.",
    "Séneca (para cerrar el círculo): Lánguida es la felicidad que no tiene enemigos.",
  ],
  'TIEMPO': [
    "Séneca: No es que tengamos poco tiempo, sino que perdemos mucho.",
    "Marco Aurelio: El tiempo es un río de eventos que pasan, y su corriente es fuerte.",
    "Platón: El tiempo es la imagen móvil de la eternidad.",
    "Aristóteles: El tiempo es la medida del movimiento según el antes y el después.",
    "Heráclito: Nadie se baña dos veces en el mismo río.",
    "Séneca: La vida es larga si sabes cómo usarla.",
    "Epicuro: El sabio no teme al tiempo, pues el placer no aumenta con la duración.",
    "Marco Aurelio: No actúes como si fueras a vivir diez mil años. El destino pende sobre ti.",
    "Cicerón: El tiempo lo borra todo, pero la verdad permanece.",
    "Ovidio: El tiempo es el devorador de todas las cosas.",
    "Séneca: Mientras esperamos vivir, la vida pasa.",
    "Plutarco: El tiempo es el más sabio de todos los consejeros.",
    "Heráclito: El tiempo es un niño que juega a los dados.",
    "Virgilio: Tempus fugit (El tiempo huye).",
    "Horacio: Carpe diem (Cosecha el día).",
    "Jorge Luis Borges: El tiempo es la sustancia de la que estoy hecho.",
    "Martin Heidegger: El ser es tiempo.",
    "Jean-Paul Sartre: El hombre es lo que hace con lo que hicieron de él en el tiempo.",
    "Friedrich Nietzsche: El presente es el punto de encuentro de la eternidad.",
    "Søren Kierkegaard: La vida solo puede ser comprendida mirando hacia atrás, pero debe ser vivida hacia adelante.",
    "Miguel de Unamuno: El tiempo es la sangre de nuestra alma.",
    "Albert Camus: No es el futuro lo que nos angustia, sino el deseo de que el presente sea eterno.",
    "Borges: El tiempo es un río que me arrebata, pero yo soy el río.",
    "Simone de Beauvoir: El tiempo es un flujo que no se detiene, pero que podemos habitar.",
    "Nietzsche: El eterno retorno: ¿vivirías este instante una y otra vez?.",
    "Heidegger: La esencia del tiempo es su finitud.",
    "Sartre: Dios es el único ser que no necesita el tiempo.",
    "Borges: El futuro no es lo que va a pasar, sino lo que vamos a hacer.",
    "Unamuno: Mañana es la mentira con que nos consolamos de hoy.",
    "José Ortega y Gasset: Yo soy yo y mi circunstancia, y si no la salvo a ella, no me salvo yo (en el tiempo).",
    "Albert Einstein: El tiempo es una ilusión, aunque sea una muy persistente.",
    "Isaac Newton: El tiempo absoluto fluye de manera uniforme sin relación con nada externo.",
    "Stephen Hawking: El tiempo comenzó con el Big Bang; no hay un 'antes'.",
    "Blaise Pascal: El presente nunca es nuestro fin. El pasado y el presente son medios; solo el futuro es nuestro fin.",
    "Immanuel Kant: El tiempo no es algo que exista por sí mismo, sino una forma de nuestra percepción.",
    "Gottfried Leibniz: El tiempo es el orden de las sucesiones.",
    "Arthur Eddington: La flecha del tiempo apunta hacia el aumento del desorden.",
    "Henri Bergson: El tiempo real es la duración vivida, no el tiempo del reloj.",
    "Einstein: Cuando cortejas a una chica bella, una hora parece un segundo. Cuando te sientas sobre carbón ardiendo, un segundo parece una hora.",
    "Carl Sagan: Somos el medio para que el cosmos se conozca a sí mismo a través del tiempo.",
    "Baruch Spinoza: La eternidad no es duración, sino una forma del pensamiento.",
    "David Hume: El tiempo es solo una sucesión de ideas e impresiones.",
    "Richard Feynman: El tiempo es lo que ocurre cuando no pasa nada más.",
    "Stephen Hawking: Incluso si el tiempo se detuviera, el universo seguiría ahí.",
    "Blaise Pascal: Nuestra naturaleza está en el movimiento; el reposo absoluto es la muerte.",
    "Buda: El problema es que crees que tienes tiempo.",
    "Lao Tsé: La naturaleza no se apresura, sin embargo, todo se logra.",
    "Proverbio Zen: Si tienes un ojo en el pasado y otro en el futuro, estarás bizco en el presente.",
    "Confucio: No importa lo lento que vayas, siempre y cuando no te detengas.",
    "Dōgen: El tiempo mismo es ser, y todo ser es tiempo.",
    "Rumi: Ayer era inteligente, por eso quería cambiar el mundo. Hoy soy sabio, por eso me cambio a mí mismo.",
    "Lao Tsé: Si estás deprimido, vives en el pasado. Si estás ansioso, vives en el futuro.",
    "Gandhi: El futuro depende de lo que hagas hoy.",
    "Proverbio Chino: El mejor momento para plantar un árbol fue hace 20 años. El segundo mejor momento es ahora.",
    "Krishnamurti: La libertad es encontrarse en el presente sin el peso del pasado.",
    "Zhuangzi: El hombre sabio no mide el tiempo, sino la profundidad de sus actos.",
    "Buda: Cada mañana nacemos de nuevo. Lo que hacemos hoy es lo que más importa.",
    "Sun Tzu: El tiempo es el recurso más crítico para la victoria.",
    "Proverbio Japonés: Incluso una piedra de mil años puede ser movida por un solo instante.",
    "Rabindranath Tagore: No puedes cruzar el mar simplemente mirando el agua.",
    "William Shakespeare: El tiempo es muy lento para los que esperan, muy rápido para los que temen.",
    "Marcel Proust: El tiempo que tenemos a nuestra disposición es elástico.",
    "Antonio Machado: Hoy es siempre todavía.",
    "Octavio Paz: El presente es el único tiempo de que disponemos.",
    "Victor Hugo: El futuro tiene muchos nombres. Para los débiles es lo inalcanzable. Para los temerosos, lo desconocido. Para los valientes es la oportunidad.",
    "T.S. Eliot: El tiempo presente y el tiempo pasado están ambos presentes en el tiempo futuro.",
    "Charles Baudelaire: ¡Oh Tiempo! ¡Devorador de los hombres!.",
    "Emily Dickinson: Para siempre está compuesto de muchos ahoras.",
    "Fedor Dostoievski: El hombre es un animal que se acostumbra a todo, incluso al paso del tiempo.",
    "Gabriel García Márquez: El tiempo no pasa, sino que da vueltas en redondo.",
    "Franz Kafka: El tiempo es un camino que no termina.",
    "Lope de Vega: El tiempo lo que no puede, el tiempo lo que no cura.",
    "Oscar Wilde: La única forma de vencer al tiempo es a través del arte.",
    "Virginia Woolf: El tiempo pasa, pero las personas cambian más lento.",
    "Pablo Neruda: Nosotros, los de entonces, ya no somos los mismos.",
    "Benjamin Franklin: El tiempo es dinero.",
    "Arthur Schopenhauer: La gente común solo piensa en cómo pasar el tiempo; un hombre de talento trata de usarlo.",
    "San Agustín: ¿Qué es el tiempo? Si nadie me lo pregunta, lo sé; si quiero explicarlo, no lo sé.",
    "Francis Bacon: Para dominar la naturaleza hay que obedecerla (y a sus tiempos).",
    "Thomas Jefferson: No dejes para mañana lo que puedas hacer hoy.",
    "Erasmo de Rotterdam: El tiempo es el padre de la verdad.",
    "Miguel de Cervantes: Confía en el tiempo, que suele dar dulces salidas a muchas amargas dificultades.",
    "Elias Canetti: El tiempo es la única cosa que no se puede poseer.",
    "Milan Kundera: El tiempo no corre, sino que se despliega.",
    "Hannah Arendt: El perdón es la única manera de revertir el pasado.",
    "Bertrand Russell: El tiempo que disfrutas perdiendo no es tiempo perdido.",
    "Steve Jobs: Tu tiempo es limitado, así que no lo malgastes viviendo la vida de otro.",
    "G.K. Chesterton: No hay días aburridos, solo personas que no miran el tiempo con asombro.",
    "C.S. Lewis: El futuro es algo que cada uno alcanza a un ritmo de sesenta minutos por hora.",
    "Baltasar Gracián: Todo lo que realmente nos pertenece es el tiempo; incluso aquel que no tiene nada más, lo tiene.",
    "Epicuro: La muerte no nos concierne, pues mientras existimos, ella no está; y cuando ella llega, nosotros ya no somos.",
    "William Faulkner: El pasado nunca muere. Ni siquiera es pasado.",
    "Friedrich Schiller: Tres veces camina el tiempo: lento el futuro, veloz el presente, inmóvil el pasado.",
    "Anaximandro: Las cosas perecen según la necesidad, pues se rinden cuentas por sus injusticias según el orden del tiempo.",
    "Paul Valéry: El problema de nuestro tiempo es que el futuro ya no es lo que solía ser.",
    "Henry David Thoreau: El tiempo no es sino el río en el que voy a pescar.",
    "Emil Cioran: Estamos todos en el fondo de un infierno, cada instante del cual es un milagro.",
    "Sigmund Freud: En el inconsciente, el tiempo no existe.",
    "Ludwig Wittgenstein: Si por eternidad se entiende no una duración infinita sino la falta de tiempo, entonces vive eternamente quien vive en el presente.",
    "Anónimo: El tiempo es el único juez que nunca se equivoca.",
  ],
  'SOLEDAD': [
    "La soledad es la suerte de todos los espíritus excelentes. — Arthur Schopenhauer.",
    "Un hombre puede ser él mismo solo mientras esté solo. — Arthur Schopenhauer.",
    "La soledad es el lugar donde se encuentran las verdades. — Séneca.",
    "El hombre que no sabe estar solo, no sabe ser libre. — Séneca.",
    "Quien no ama la soledad, no ama la libertad. — Arthur Schopenhauer.",
    "La soledad es para el espíritu lo que la dieta es para el cuerpo. — Luc de Clapiers.",
    "Vivir solo es el destino de todas las almas grandes. — Aldous Huxley.",
    "La soledad es el imperio de la conciencia. — Gustavo Adolfo Bécquer.",
    "En la soledad, el solitario se devora a sí mismo; en la multitud, lo devoran los muchos. — Friedrich Nietzsche.",
    "Solo en la soledad se siente la sed de la verdad. — María Zambrano.",
    "Estamos solos, sin excusas. — Jean-Paul Sartre.",
    "El infierno son los otros. — Jean-Paul Sartre.",
    "Nacemos solos, vivimos solos, morimos solos. — Orson Welles.",
    "La soledad es el fondo último de la condición humana. — Octavio Paz.",
    "El hombre está condenado a ser libre. — Jean-Paul Sartre.",
    "La verdadera soledad es vivir entre todas estas personas amables que solo te piden que finjas. — Edith Wharton.",
    "Sentirse solo entre la gente es la peor forma de soledad. — Fiódor Dostoyevski.",
    "La soledad es una forma de libertad que a veces pesa demasiado. — Albert Camus.",
    "Nadie puede construir por ti el puente sobre el cual debes cruzar el río de la vida. — Friedrich Nietzsche.",
    "Cada uno de nosotros está en una burbuja de soledad. — Jean Baudrillard.",
    "La soledad es la presencia de uno mismo. — Mary Sarton.",
    "La desolación es la soledad que duele. — Paul Tillich.",
    "Nunca encontré una compañera tan sociable como la soledad. — Henry David Thoreau.",
    "Si te sientes solo cuando estás solo, estás en mala compañía. — Jean-Paul Sartre.",
    "Estar solo no es lo mismo que estar solitario. — Osho.",
    "La soledad es un estado de plenitud, la desolación es un estado de vacío. — Anthony de Mello.",
    "El solitario es un disminuido, el que sabe estar solo es un hombre completo. — Jiddu Krishnamurti.",
    "A veces es necesario retirarse del mundo para poder verlo. — Thomas Merton.",
    "La soledad es un jardín donde el alma florece. — Proverbio sufí.",
    "No hay nada más solitario que un matrimonio infeliz. — Anónimo.",
    "El secreto de una buena vejez no es otra cosa que un pacto honrado con la soledad. — Gabriel García Márquez.",
    "La soledad era el aire que ella respiraba. — Gabriel García Márquez.",
    "La soledad es muy hermosa... cuando se tiene alguien a quien decírselo. — Gustavo Adolfo Bécquer.",
    "Mi soledad no tiene nada que ver con la presencia o ausencia de personas. — James Baldwin.",
    "Escribo para estar solo, y porque estoy solo. — Fernando Pessoa.",
    "A veces el silencio es la conversación más profunda. — Paulo Coelho.",
    "La soledad es el precio de la libertad. — Carmen Alborch.",
    "Todo lo que es grande se hace en la soledad. — Maurice Maeterlinck.",
    "Andábamos sin buscarnos, pero sabiendo que andábamos para encontrarnos. — Julio Cortázar.",
    "Me gusta mi soledad, pero prefiero compartirla contigo. — Jorge Bucay.",
    "El silencio es el sueño que nutre la sabiduría. — Francis Bacon.",
    "La palabra es plata, el silencio es oro. — Proverbio antiguo.",
    "En el silencio, el hombre escucha su propia voz. — C.G. Jung.",
    "La soledad es el taller de la deidad. — Proverbio hindú.",
    "Quien no comprende tu silencio, probablemente no comprenderá tus palabras. — Elbert Hubbard.",
    "La meditación es el arte de estar solo sin sentirse solo. — Osho.",
    "El ruido exterior solo oculta el vacío interior. — Blaise Pascal.",
    "Todas las desgracias del hombre derivan de no saber quedarse tranquilo en una habitación. — Blaise Pascal.",
    "La soledad es el eco de un alma que busca su centro. — Ralph Waldo Emerson.",
    "Solo en el silencio puedes escuchar lo que el universo tiene que decirte. — Rumi.",
    "Quien es capaz de vivir solo es una bestia o un dios. — Aristóteles.",
    "Retírate dentro de ti mismo, pero primero prepárate para recibirte. — Epicteto.",
    "Busca la soledad, pero no huyas de los hombres. — Marco Aurelio.",
    "La felicidad consiste en no necesitar a nadie. — Epicuro.",
    "Aquel que tiene un 'porqué' para vivir, puede soportar casi cualquier 'cómo'. — Viktor Frankl (citando a Nietzsche).",
    "La soledad es un refugio para el sabio y una cárcel para el necio. — Proverbio latino.",
    "El sabio se basta a sí mismo. — Séneca.",
    "Nada es tan insoportable para el hombre como estar en pleno reposo, sin pasiones, sin quehacer, sin diversión. — Blaise Pascal.",
    "El que se busca a sí mismo en los demás, nunca se encuentra. — Lao Tzu.",
    "La quietud es la madre de todas las cosas. — Lao Tzu.",
    "La soledad es el hambre del alma por la conexión. — Anónimo.",
    "El peor sentimiento no es estar solo, sino estar olvidado por alguien que no puedes olvidar. — Anónimo.",
    "La soledad es un monstruo que devora la esperanza. — Victor Hugo.",
    "No hay soledad más triste que la de un hombre sin amigos. — Francis Bacon.",
    "La soledad duele cuando no la has elegido. — Erich Fromm.",
    "El hombre es un animal social, y la soledad es su castigo. — Aristóteles.",
    "La soledad es una enfermedad que se cura con amor, pero se previene con amistad. — Anónimo.",
    "Morir es estar solo para siempre. — Emily Dickinson.",
    "La soledad es el frío del alma. — Friedrich Schiller.",
    "A veces, el vacío es tan grande que no cabe en el pecho. — Anónimo.",
    "Hoy estamos más conectados que nunca, pero más solos que siempre. — Zygmunt Bauman.",
    "La soledad electrónica es la más profunda de todas. — Sherry Turkle.",
    "El consumo es una forma de llenar el vacío de la soledad. — Erich Fromm.",
    "Vivimos en una sociedad de la exposición donde la soledad es vista como un fracaso. — Byung-Chul Han.",
    "El individualismo nos ha dejado solos en una multitud. — Gilles Lipovetsky.",
    "La soledad no es la falta de compañía, sino la falta de propósito compartido. — Hannah Arendt.",
    "En las redes sociales, la soledad se disfraza de 'likes'. — Anónimo.",
    "La soledad moderna es el silencio entre dos notificaciones. — Anónimo.",
    "Nadie está más solo que aquel que siempre está 'disponible'. — Anónimo.",
    "La verdadera conexión requiere el riesgo de la soledad. — Thomas Moore.",
    "Sin una gran soledad, ningún trabajo serio es posible. — Pablo Picasso.",
    "La creatividad nace del silencio. — Wolfgang Amadeus Mozart.",
    "Estar solo es el secreto de la invención; estar solo es cuando nacen las ideas. — Nikola Tesla.",
    "El arte es el hijo de la soledad. — Marcel Proust.",
    "Solo en la soledad la mente se agudiza. — Isaac Newton.",
    "La inspiración necesita paz, y la paz necesita soledad. — Virginia Woolf.",
    "El genio vive en la soledad, el talento en la sociedad. — Maurice Barrès.",
    "La escritura es una soledad compartida. — Marguerite Duras.",
    "La música es la soledad que se vuelve sonido. — Anónimo.",
    "Para crear, uno debe ser capaz de estar solo consigo mismo. — Louise Bourgeois.",
    "Soledad: un buen lugar para visitar, pero un mal lugar para quedarse. — Josh Billings.",
    "La soledad es el precio de la originalidad.",
    "Solo el solitario conoce la verdadera alegría de la compañía.",
    "La soledad es el espejo del alma.",
    "No temas a la soledad; témele a la mala compañía.",
    "La soledad es un maestro severo pero justo.",
    "Estar solo es un arte; sentirse solo es una tragedia.",
    "La soledad es el puente hacia lo divino.",
    "Quien se tiene a sí mismo, nunca está solo.",
    "La soledad es, al final, nuestro único hogar verdadero.",
  ],
};
